Remove timeout for upgrade app downtime monitoring
SUSE/cf-ci pull request #353
Opened 2020-01-15 03:33 UTC by HartS

If the app isn't back online, we have problems with the upgrade, so we
should keep monitoring until the cf-upgrade task timeout hits (or helm
upgrade timeout if applicable). Monitoring should not complete
successfully unless the app is back up.

2020-01-15 21:36 UTC, prabalsharma commented
so the upgrade task timeout is 5hours. I think instead of removing timeout from monitoring we should exit 1. This will give us more info more quickly

`    if [[ ${count} -gt 10800 ]]; then	
      echo "Ending monitor of ${app_url} due to timeout"	
      exit 1
    fi`

2020-01-15 23:21 UTC, prabalsharma requested changes
so the upgrade task timeout is 5hours. I think instead of removing timeout from monitoring we should exit 1. This will give us more info more quickly

```   if [[ ${count} -gt 10800 ]]; then	
      echo "Ending monitor of ${app_url} due to timeout"	
      exit 1
    fi

2020-01-16 23:15 UTC, HartS commented
@prabalsharma it's true that downtime really shouldn't be that long, but in the event of slow image pulls combined with other defects which might cause excessively long upgrades (and therefore, app downtime), it may be valuable to know where things are going wrong, rather than timing out the app monitoring.

Also, since this is backgrounded, exiting with status 1 won't actually fail the test, so the timeout is irrelevant; I don't see any reason not to continue monitoring as long as the application is not ready post-upgrade

2020-01-16 23:55 UTC, prabalsharma approved these changes

2020-01-16 23:55 UTC, merged